version: '3.1'

services:
  mysql:
    image: mysql:8.0
    restart: always
    ports:
     - '3306:3306'
    environment:
      MYSQL_DATABASE: 'em-test-db'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
    driver: local
